/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2017-12-01 07:44:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contents_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1507863366000L));
    _jspx_dependants.put("jar:file:/C:/!SHOU/work/jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mini2-home/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/!SHOU/work/jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mini2-home/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<div class=\"dashboard display-animation\"\r\n");
      out.write("\tstyle=\"margin: 0 auto; width: 1130px;\">\r\n");
      out.write("\t<div class=\"tile tile-lg tile-pink ripple-effect\">\r\n");
      out.write("\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"tile-content\">\r\n");
      out.write("\t\t\t\t<div class=\"tile-holder tile-holder-sm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">최근 게시물 목록</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<table class=\"sortable\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-sort=\"name\">작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-sort=\"title\">제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th data-sort=\"date\">날짜</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t<button class=\"hover\" style=\"float: right;\"><i class=\"fa fa-plus-square-o\" aria-hidden=\"true\"></i>더보기</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"tile tile-lg tile-sqr tile-purple ripple-effect\">\r\n");
      out.write("\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"tile-content\">\r\n");
      out.write("\t\t\t\t<div class=\"tile-holder tile-holder-sm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">공지사항</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"w3-container\">\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"w3-panel w3-pale-green w3-bottombar w3-border-green w3-border\">\r\n");
      out.write("\t\t\t\t\t\t<p id=\"noticeContents\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${notice.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button\r\n");
      out.write("\t\t\t\t\tonclick=\"document.getElementById('notice').style.display='block'\"\r\n");
      out.write("\t\t\t\t\tclass=\"w3-button w3-black\">새로 작성</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"tile tile-lg tile-sqr tile-cyan ripple-effect\">\r\n");
      out.write("\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"tile-content\">\r\n");
      out.write("\t\t\t\t<div class=\"tile-holder tile-holder-sm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">오늘의 내기</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"todayDealTitle\" class=\"caption\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"color: black; padding: 3px;\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"title\">상품</p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${todayDeal.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"w3-container\">\r\n");
      out.write("\t\t\t\t\t<div class=\"w3-panel w3-border w3-light-grey w3-round-large\">\r\n");
      out.write("\t\t\t\t\t\t<p id=\"todayDealContents\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${todayDeal.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button\r\n");
      out.write("\t\t\t\t\tonclick=\"document.getElementById('todayDeal').style.display='block'\"\r\n");
      out.write("\t\t\t\t\tclass=\"w3-button w3-black\">작성</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"tile tile-lg tile-sqr tile-red ripple-effect\">\r\n");
      out.write("\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"tile-content\">\r\n");
      out.write("\t\t\t\t<div class=\"tile-holder tile-holder-sm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">출석률</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div ng-app=\"myApp\">\r\n");
      out.write("\t\t\t\t\t<bars data=\"40,4,55,15,16,33,52,20,35,67,45,32,45,32,78,88\"></bars>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<p>한달 기준</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"tile tile-lg tile-light-blue ripple-effect\">\r\n");
      out.write("\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"tile-content\" style=\"padding-top: 12px;\">\r\n");
      out.write("\t\t\t\t<div class=\"tile-holder tile-holder-sm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">달력</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"calendar-container\">\r\n");
      out.write("\t\t\t\t\t<div id=\"calendar-header\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"calendar-header-box calendar-button\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"calendarBack()\"> <i class=\"fa fa-angle-left\"></i>\r\n");
      out.write("\t\t\t\t\t\t</span> <span id=\"calendar-year-title\" class=\"calendar-header-box year\">2017</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"calendar-header-box calendar-button\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"calendarNext()\"> <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"calendar-wrapper\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"tile tile-lg tile-sqr tile-amber ripple-effect\">\r\n");
      out.write("\t\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"tile-content\">\r\n");
      out.write("\t\t\t\t<div class=\"tile-holder tile-holder-sm\">\r\n");
      out.write("\t\t\t\t\t<div class=\"title\">Support Link</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"social-platforms\">\r\n");
      out.write("\t\t\t\t\t<a class=\"btn btn-icon btn-facebook\" href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-facebook\"></i><span>Facebook</span></a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-icon btn-twitter\" href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-twitter\"></i><span>Twitter</span></a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-icon btn-googleplus\" href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-google\"></i><span>Google+</span></a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-icon btn-pinterest\" href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-pinterest\"></i><span>Pinterest</span></a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-icon btn-linkedin\" href=\"#\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-linkedin\"></i><span>LinkedIn</span></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 모달 부분 ------------------------------------------------------------------------->\r\n");
      out.write("<!-- 모달 부분 ------------------------------------------------------------------------->\r\n");
      out.write("<!-- 모달 부분 ------------------------------------------------------------------------->\r\n");
      out.write("\r\n");
      out.write("<div id=\"notice\" class=\"w3-modal\">\r\n");
      out.write("\t<div class=\"w3-modal-content\">\r\n");
      out.write("\t\t<header class=\"w3-container w3-red\"> <span\r\n");
      out.write("\t\t\tonclick=\"document.getElementById('notice').style.display='none'\"\r\n");
      out.write("\t\t\tclass=\"w3-button w3-display-topright\">&times;</span>\r\n");
      out.write("\t\t<h2>공지사항</h2>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"w3-container\">\r\n");
      out.write("\t\t\t<input id=\"noticeForm\" class=\"w3-input w3-border w3-light-grey\"\r\n");
      out.write("\t\t\t\ttype=\"text\" style=\"width: 870px; height: 200px;\" placeholder=\"내용 입력\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<button id=\"noticeWrite\" class=\"w3-button w3-black w3-round-large\">작성</button>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"todayDeal\" class=\"w3-modal\">\r\n");
      out.write("\t<div class=\"w3-modal-content\">\r\n");
      out.write("\t\t<header class=\"w3-container w3-teal\"> <span\r\n");
      out.write("\t\t\tonclick=\"document.getElementById('todayDeal').style.display='none'\"\r\n");
      out.write("\t\t\tclass=\"w3-button w3-display-topright\">&times;</span>\r\n");
      out.write("\t\t<h2>오늘의 내기</h2>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"w3-container\">\r\n");
      out.write("\t\t\t<input id=\"todayDealForm\" class=\"w3-input w3-border w3-light-grey\"\r\n");
      out.write("\t\t\t\ttype=\"text\" style=\"width: 870px; height: 200px;\" placeholder=\"내용 입력\">\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t\t<input id=\"todayDealTitleForm\"\r\n");
      out.write("\t\t\t\tclass=\"w3-input w3-border w3-light-grey\" type=\"text\"\r\n");
      out.write("\t\t\t\tplaceholder=\"상품 입력\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t<button id=\"todayDealWrite\" class=\"w3-button w3-black w3-round-large\">입력</button>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar path = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\r\n");
      out.write("\t$(\"#noticeWrite\").on(\"click\", function(e) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : path + \"/main/notice.json\",\r\n");
      out.write("\t\t\tdata : \"contents=\" + $(\"#noticeForm\").val() + \"&categoryNo=6\",\r\n");
      out.write("\t\t\tsuccess : function() {\r\n");
      out.write("\t\t\t\tdocument.getElementById('notice').style.display = 'none';\r\n");
      out.write("\t\t\t\t$(\"#noticeContents\").text($(\"#noticeForm\").val());\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#todayDealWrite\")\r\n");
      out.write("\t\t\t.on(\"click\", function(e) {\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\turl : path + \"/main/todayDeal.json\",\r\n");
      out.write("\t\t\t\t\t\tdata : \"contents=\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ $(\"#todayDealForm\").val()\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"&categoryNo=7&title=\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ $(\"#todayDealTitleForm\").val(),\r\n");
      out.write("\t\t\t\t\t\tsuccess : function() {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('todayDeal').style.display = 'none';\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#todayDealContents\").text($(\"#todayDealForm\").val());\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#todayDealTitle\").text($(\"#todayDealTitleForm\").val());\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t/////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("\t/////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("\t/////////////////////////////////////////////////////////////////////////////\r\n");
      out.write("\r\n");
      out.write("\tDate.prototype.addDays = function(days) {\r\n");
      out.write("\t\tvar dat = new Date(this.valueOf())\r\n");
      out.write("\t\tdat.setDate(dat.getDate() + days);\r\n");
      out.write("\t\treturn dat;\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tvar focusDate = new Date();\r\n");
      out.write("\tvar today = new Date();\r\n");
      out.write("\r\n");
      out.write("\twindow.onload = function() {\r\n");
      out.write("\t\tvar container = document.getElementById(\"calendar-wrapper\");\r\n");
      out.write("\r\n");
      out.write("\t\tmakeCalendar(true, focusDate);\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tfunction calendarBack() {\r\n");
      out.write("\t\tvar fadeOutTable = document.getElementsByClassName(\"calendar-table3\")[0];\r\n");
      out.write("\t\tfadeOutTable.classList.add(\"calendar-animation-drop\");\r\n");
      out.write("\t\twindow.setTimeout(function() {\r\n");
      out.write("\t\t\tvar newYear = focusDate.getFullYear();\r\n");
      out.write("\t\t\tvar newMonth = focusDate.getMonth() - 1;\r\n");
      out.write("\t\t\tif (newMonth == 0) {\r\n");
      out.write("\t\t\t\tnewMonth = 12;\r\n");
      out.write("\t\t\t\tnewYear--;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfocusDate.setYear(newYear);\r\n");
      out.write("\t\t\tfocusDate.setMonth(newMonth);\r\n");
      out.write("\t\t\tmakeCalendar(true, focusDate, false);\r\n");
      out.write("\t\t}, 300);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction calendarNext() {\r\n");
      out.write("\t\tvar fadeOutTable = document.getElementsByClassName(\"calendar-table1\")[0];\r\n");
      out.write("\t\tfadeOutTable.classList.add(\"calendar-animation-drop\");\r\n");
      out.write("\t\twindow.setTimeout(function() {\r\n");
      out.write("\t\t\tvar newYear = focusDate.getFullYear();\r\n");
      out.write("\t\t\tvar newMonth = focusDate.getMonth() + 1;\r\n");
      out.write("\t\t\tif (newMonth == 12) {\r\n");
      out.write("\t\t\t\tnewMonth = 0;\r\n");
      out.write("\t\t\t\tnewYear++;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfocusDate.setYear(newYear);\r\n");
      out.write("\t\t\tfocusDate.setMonth(newMonth);\r\n");
      out.write("\t\t\tmakeCalendar(true, focusDate, true);\r\n");
      out.write("\t\t}, 300);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction makeCalendar(isTriple, fDate, isNext) {\r\n");
      out.write("\t\tvar elements = document.getElementsByClassName(\"calendar\");\r\n");
      out.write("\t\twhile (elements.length > 0) {\r\n");
      out.write("\t\t\telements[0].parentNode.removeChild(elements[0]);\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tdocument.getElementById(\"calendar-year-title\").innerHTML = fDate\r\n");
      out.write("\t\t\t\t.getFullYear();\r\n");
      out.write("\r\n");
      out.write("\t\tif (!isTriple) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"calendar-wrapper\").appendChild(\r\n");
      out.write("\t\t\t\t\tgetCalendarTable(focusDate.getFullYear(), focusDate\r\n");
      out.write("\t\t\t\t\t\t\t.getMonth() + 1));\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tvar tableToEdit = getCalendarTable(focusDate.getFullYear(),\r\n");
      out.write("\t\t\t\t\tfocusDate.getMonth());\r\n");
      out.write("\t\t\ttableToEdit.classList.add(\"calendar-dim\");\r\n");
      out.write("\t\t\ttableToEdit.classList.add(\"calendar-table1\");\r\n");
      out.write("\t\t\tif (isNext) {\r\n");
      out.write("\t\t\t\ttableToEdit.classList.add(\"calendar-animation-leftFadeOut\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\ttableToEdit.classList.add(\"calendar-animation-right\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(\"calendar-wrapper\")\r\n");
      out.write("\t\t\t\t\t.appendChild(tableToEdit);\r\n");
      out.write("\t\t\taddBreak();\r\n");
      out.write("\t\t\ttableToEdit = getCalendarTable(focusDate.getFullYear(), focusDate\r\n");
      out.write("\t\t\t\t\t.getMonth() + 1);\r\n");
      out.write("\t\t\ttableToEdit.classList.add(\"calendar-table2\");\r\n");
      out.write("\t\t\tif (isNext) {\r\n");
      out.write("\t\t\t\ttableToEdit.classList.add(\"calendar-animation-leftFade\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\ttableToEdit.classList.add(\"calendar-animation-rightFade\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(\"calendar-wrapper\")\r\n");
      out.write("\t\t\t\t\t.appendChild(tableToEdit);\r\n");
      out.write("\t\t\taddBreak();\r\n");
      out.write("\t\t\ttableToEdit = getCalendarTable(focusDate.getFullYear(), focusDate\r\n");
      out.write("\t\t\t\t\t.getMonth() + 2);\r\n");
      out.write("\t\t\ttableToEdit.classList.add(\"calendar-dim\");\r\n");
      out.write("\t\t\ttableToEdit.classList.add(\"calendar-table3\");\r\n");
      out.write("\t\t\tif (isNext) {\r\n");
      out.write("\t\t\t\ttableToEdit.classList.add(\"calendar-animation-left\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\ttableToEdit.classList.add(\"calendar-animation-rightFadeOut\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(\"calendar-wrapper\")\r\n");
      out.write("\t\t\t\t\t.appendChild(tableToEdit);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tfunction addBreak() {\r\n");
      out.write("\t\tvar breakElement = document.createElement('div');\r\n");
      out.write("\t\tbreakElement.classList.add(\"calendar-table-break\");\r\n");
      out.write("\t\tbreakElement.classList.add(\"calendar\");\r\n");
      out.write("\t\tvar breakElementChild = document.createElement('div');\r\n");
      out.write("\t\tbreakElementChild.classList.add(\"calendar-table-break-child\");\r\n");
      out.write("\t\tbreakElement.appendChild(breakElementChild);\r\n");
      out.write("\t\tdocument.getElementById(\"calendar-wrapper\").appendChild(breakElement);\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tfunction getCalendarTable(year, month) {\r\n");
      out.write("\t\tif (month == 0) {\r\n");
      out.write("\t\t\tmonth = 12;\r\n");
      out.write("\t\t\tyear--;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (month == 13) {\r\n");
      out.write("\t\t\tmonth = 1;\r\n");
      out.write("\t\t\tyear++;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t// Safari fix\r\n");
      out.write("\t\tif (month < 10) {\r\n");
      out.write("\t\t\tmonth = \"0\" + month;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar calendarDate = new Date(year + \"-\" + month + \"-01\");\r\n");
      out.write("\t\tvar firstDay = calendarDate.getDay();\r\n");
      out.write("\t\tvar numberOfDays = new Date(calendarDate.getFullYear(), calendarDate\r\n");
      out.write("\t\t\t\t.getMonth() + 1, 0).getDate();\r\n");
      out.write("\r\n");
      out.write("\t\tvar monthNameArray = [ \"January\", \"February\", \"March\", \"April\", \"May\",\r\n");
      out.write("\t\t\t\t\"June\", \"July\", \"August\", \"September\", \"October\", \"November\",\r\n");
      out.write("\t\t\t\t\"December\" ];\r\n");
      out.write("\r\n");
      out.write("\t\t// Create HTML Table\r\n");
      out.write("\t\tvar table = document.createElement('table');\r\n");
      out.write("\t\ttable.classList.add(\"calendar\");\r\n");
      out.write("\t\tvar heading = document.createElement('div');\r\n");
      out.write("\t\theading.classList.add(\"calendar-month-heading\");\r\n");
      out.write("\t\theading.innerHTML = monthNameArray[month - 1];\r\n");
      out.write("\t\theading.style = \"width : 10px\";\r\n");
      out.write("\t\ttable.appendChild(heading);\r\n");
      out.write("\t\tvar tr = document.createElement('tr');\r\n");
      out.write("\t\ttr.style = \"width=15px\";\r\n");
      out.write("\t\ttr.classList.add(\"calendar\");\r\n");
      out.write("\r\n");
      out.write("\t\t// Day Letters\r\n");
      out.write("\t\tfor (var i = 0; i < 7; i++) {\r\n");
      out.write("\t\t\tvar th = document.createElement('th');\r\n");
      out.write("\t\t\tth.classList.add(\"calendar\");\r\n");
      out.write("\t\t\tth.innerHTML = \"SMTWTFS\"[i];\r\n");
      out.write("\t\t\tth.style = \"width=15px\";\r\n");
      out.write("\t\t\tif (i == 0) {\r\n");
      out.write("\t\t\t\tth.style = \"color : red\";\r\n");
      out.write("\t\t\t} else if (i == 6) {\r\n");
      out.write("\t\t\t\tth.style = \"color : blue\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ttr.appendChild(th);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ttable.appendChild(tr);\r\n");
      out.write("\r\n");
      out.write("\t\t// Week 1\r\n");
      out.write("\t\ttr = document.createElement('tr');\r\n");
      out.write("\t\ttr.classList.add(\"calendar\");\r\n");
      out.write("\t\tvar i = 0;\r\n");
      out.write("\t\tfor (; i < 7; i++) {\r\n");
      out.write("\t\t\tif (i == firstDay) {\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar td = document.createElement('td');\r\n");
      out.write("\t\t\ttd.classList.add(\"calendar\");\r\n");
      out.write("\t\t\ttd.innerHTML = \"\";\r\n");
      out.write("\t\t\ttr.appendChild(td);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ttable.appendChild(tr);\r\n");
      out.write("\r\n");
      out.write("\t\tvar dayNumber = 1;\r\n");
      out.write("\t\tfor (; i < 7; i++) {\r\n");
      out.write("\t\t\tvar td = document.createElement('td');\r\n");
      out.write("\t\t\ttd.classList.add(\"calendar\");\r\n");
      out.write("\t\t\tprocessDay(td, calendarDate, dayNumber);\r\n");
      out.write("\t\t\ttd.innerHTML = dayNumber;\r\n");
      out.write("\t\t\tif (i == 0) {\r\n");
      out.write("\t\t\t\ttd.style = \"color : red\";\r\n");
      out.write("\t\t\t} else if (i == 6) {\r\n");
      out.write("\t\t\t\ttd.style = \"color : blue\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdayNumber++;\r\n");
      out.write("\t\t\ttr.appendChild(td);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ttable.appendChild(tr);\r\n");
      out.write("\r\n");
      out.write("\t\t// Other Weeks\r\n");
      out.write("\t\tfor (var r = 3; r <= 7; r++) {\r\n");
      out.write("\t\t\ttr = document.createElement('tr');\r\n");
      out.write("\t\t\ttr.classList.add(\"calendar\");\r\n");
      out.write("\t\t\tfor (var i = 0; i < 7; i++) {\r\n");
      out.write("\t\t\t\tif (dayNumber > numberOfDays) {\r\n");
      out.write("\t\t\t\t\ttable.appendChild(tr);\r\n");
      out.write("\t\t\t\t\treturn table;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar td = document.createElement('td');\r\n");
      out.write("\t\t\t\ttd.classList.add(\"calendar\");\r\n");
      out.write("\t\t\t\tif (i == 0) {\r\n");
      out.write("\t\t\t\t\ttd.style = \"color : red\";\r\n");
      out.write("\t\t\t\t} else if (i == 6) {\r\n");
      out.write("\t\t\t\t\ttd.style = \"color : blue\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tprocessDay(td, calendarDate, dayNumber);\r\n");
      out.write("\t\t\t\ttd.innerHTML = dayNumber;\r\n");
      out.write("\t\t\t\tdayNumber++;\r\n");
      out.write("\t\t\t\ttr.appendChild(td);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\ttable.appendChild(tr);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn table;\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tvar seasons = [\r\n");
      out.write("\t\t\tnew DaysRange(new Date(\"2016-11-25\"), new Date(\"2017-01-20\"),\r\n");
      out.write("\t\t\t\t\t\"peak\"),\r\n");
      out.write("\t\t\tnew DaysRange(new Date(\"2017-01-21\"), new Date(\"2017-02-02\"),\r\n");
      out.write("\t\t\t\t\t\"high\") ];\r\n");
      out.write("\r\n");
      out.write("\tvar bookings = [\r\n");
      out.write("\t\t\tnew DaysRange(new Date(\"2017-01-11\"), new Date(\"2017-01-16\"),\r\n");
      out.write("\t\t\t\t\t\"booked\"),\r\n");
      out.write("\t\t\tnew DaysRange(new Date(\"2017-01-16\"), new Date(\"2017-01-28\"),\r\n");
      out.write("\t\t\t\t\t\"pending\"),\r\n");
      out.write("\t\t\tnew DaysRange(new Date(\"2016-12-23\"), new Date(\"2017-01-04\"),\r\n");
      out.write("\t\t\t\t\t\"booked\"),\r\n");
      out.write("\t\t\tnew DaysRange(new Date(\"2017-02-04\"), new Date(\"2017-02-22\"),\r\n");
      out.write("\t\t\t\t\t\"pending\"),\r\n");
      out.write("\t\t\tnew DaysRange(new Date(\"2017-02-22\"), new Date(\"2017-02-24\"),\r\n");
      out.write("\t\t\t\t\t\"pending\"),\r\n");
      out.write("\t\t\tnew DaysRange(new Date(\"2017-02-24\"), new Date(\"2017-03-04\"),\r\n");
      out.write("\t\t\t\t\t\"booked\") ];\r\n");
      out.write("\r\n");
      out.write("\tfunction DaysRange(startDate, endDate, name) {\r\n");
      out.write("\t\tthis.days = getDates(startDate, endDate);\r\n");
      out.write("\t\tthis.name = name;\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tfunction processDay(element, calendarDate, dayNumber) {\r\n");
      out.write("\t\tvar dayDate = new Date(calendarDate.getTime());\r\n");
      out.write("\t\tdayDate.setDate(dayNumber);\r\n");
      out.write("\r\n");
      out.write("\t\t// Highlight Today\r\n");
      out.write("\t\tif (dayDate.toDateString() == today.toDateString()) {\r\n");
      out.write("\t\t\telement.classList.add(\"calendar-daystyle-today\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar bookingName = getDateBooking(dayDate.toDateString());\r\n");
      out.write("\t\t//console.log(dayNumber + \" : \" + bookingName);\r\n");
      out.write("\t\tif (bookingName.startsWith(\"booked\")) {\r\n");
      out.write("\t\t\tif (bookingName.includes(\"_start\") && bookingName.includes(\"_end\")) {\r\n");
      out.write("\t\t\t\tif (bookingName.includes(\"pending\")) {\r\n");
      out.write("\t\t\t\t\telement.classList\r\n");
      out.write("\t\t\t\t\t\t\t.add(\"calendar-daystyle-booking-cross-pending\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\telement.classList.add(\"calendar-daystyle-booking-cross\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} else if (bookingName.includes(\"_start\")) {\r\n");
      out.write("\t\t\t\telement.classList.add(\"calendar-daystyle-booking-start\");\r\n");
      out.write("\t\t\t} else if (bookingName.includes(\"_end\")) {\r\n");
      out.write("\t\t\t\telement.classList.add(\"calendar-daystyle-booking-end\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\telement.classList.add(\"calendar-daystyle-booking-middle\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else if (bookingName.startsWith(\"pending\")) {\r\n");
      out.write("\t\t\tif (bookingName.includes(\"_start\") && bookingName.includes(\"_end\")) {\r\n");
      out.write("\t\t\t\tif (bookingName.includes(\"booked\")) {\r\n");
      out.write("\t\t\t\t\telement.classList\r\n");
      out.write("\t\t\t\t\t\t\t.add(\"calendar-daystyle-pending-cross-booking\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\telement.classList.add(\"calendar-daystyle-pending-cross\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} else if (bookingName.includes(\"_start\")) {\r\n");
      out.write("\t\t\t\telement.classList.add(\"calendar-daystyle-pending-start\");\r\n");
      out.write("\t\t\t} else if (bookingName.includes(\"_end\")) {\r\n");
      out.write("\t\t\t\telement.classList.add(\"calendar-daystyle-pending-end\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\telement.classList.add(\"calendar-daystyle-pending-middle\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tvar seasonName = getDateSeason(dayDate.toDateString());\r\n");
      out.write("\t\tif (seasonName == \"peak\") {\r\n");
      out.write("\t\t\telement.classList.add(\"calendar-daystyle-price-peak\");\r\n");
      out.write("\t\t} else if (seasonName == \"high\") {\r\n");
      out.write("\t\t\telement.classList.add(\"calendar-daystyle-price-high\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\telement.classList.add(\"calendar-daystyle-price-normal\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tfunction getDateSeason(dayDateString) {\r\n");
      out.write("\t\tvar seasonName = \"\";\r\n");
      out.write("\t\tseasons.forEach(function(season) {\r\n");
      out.write("\t\t\tseason.days.forEach(function(day) {\r\n");
      out.write("\t\t\t\tif (day == dayDateString) {\r\n");
      out.write("\t\t\t\t\tseasonName = season.name;\r\n");
      out.write("\t\t\t\t\treturn seasonName;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\treturn seasonName;\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tfunction getDateBooking(dayDateString) {\r\n");
      out.write("\t\tvar bookingName = \"\";\r\n");
      out.write("\t\tbookings.forEach(function(booking) {\r\n");
      out.write("\t\t\tvar dayNum = 1;\r\n");
      out.write("\t\t\tbooking.days.forEach(function(day) {\r\n");
      out.write("\t\t\t\tif (day == dayDateString) {\r\n");
      out.write("\t\t\t\t\tvar extra = \"\";\r\n");
      out.write("\t\t\t\t\tif (dayNum == 1) {\r\n");
      out.write("\t\t\t\t\t\textra = \"_start\";\r\n");
      out.write("\t\t\t\t\t} else if (dayNum == booking.days.length) {\r\n");
      out.write("\t\t\t\t\t\textra = \"_end\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tbookingName += booking.name + extra;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tdayNum++;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\treturn bookingName;\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\t// Get days array between 2 dates\r\n");
      out.write("\tfunction getDates(startDate, stopDate) {\r\n");
      out.write("\t\tvar dateArray = new Array();\r\n");
      out.write("\t\tvar currentDate = startDate;\r\n");
      out.write("\t\twhile (currentDate <= stopDate) {\r\n");
      out.write("\t\t\tvar dateString = currentDate.toDateString();\r\n");
      out.write("\t\t\tdateArray.push(dateString);\r\n");
      out.write("\t\t\tcurrentDate = currentDate.addDays(1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn dateArray;\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\tangular.module('myApp', []).\r\n");
      out.write("\r\n");
      out.write("\tdirective(\r\n");
      out.write("\t\t\t'bars',\r\n");
      out.write("\t\t\tfunction($parse) {\r\n");
      out.write("\t\t\t\treturn {\r\n");
      out.write("\t\t\t\t\trestrict : 'E',\r\n");
      out.write("\t\t\t\t\treplace : true,\r\n");
      out.write("\t\t\t\t\ttemplate : '<div id=\"chart\"></div>',\r\n");
      out.write("\t\t\t\t\tlink : function(scope, element, attrs) {\r\n");
      out.write("\t\t\t\t\t\tvar data = attrs.data.split(','), chart = d3.select(\r\n");
      out.write("\t\t\t\t\t\t\t\t'#chart').append(\"div\").attr(\"class\", \"chart\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.selectAll('div').data(data).enter().append(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"div\").transition().ease(\"elastic\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.style(\"width\", function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\treturn d + \"%\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}).style(\"height\", \"4px\").style(\"color\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"white\").style(\"text-shadow\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"0 0 2px black\").text(function(d) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\treturn d + \"%\";\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t/**\r\n");
      out.write("\t * Created by Kupletsky Sergey on 16.09.14.\r\n");
      out.write("\t *\r\n");
      out.write("\t * Hierarchical timing\r\n");
      out.write("\t * Add specific delay for CSS3-animation to elements.\r\n");
      out.write("\t */\r\n");
      out.write("\r\n");
      out.write("\t(function($) {\r\n");
      out.write("\t\tvar speed = 2000;\r\n");
      out.write("\t\tvar container = $('.display-animation');\r\n");
      out.write("\t\tcontainer.each(function() {\r\n");
      out.write("\t\t\tvar elements = $(this).children();\r\n");
      out.write("\t\t\telements.each(function() {\r\n");
      out.write("\t\t\t\tvar elementOffset = $(this).offset();\r\n");
      out.write("\t\t\t\tvar offset = elementOffset.left * 0.8 + elementOffset.top;\r\n");
      out.write("\t\t\t\tvar delay = parseFloat(offset / speed).toFixed(2);\r\n");
      out.write("\t\t\t\t$(this).css(\"-webkit-animation-delay\", delay + 's').css(\r\n");
      out.write("\t\t\t\t\t\t\"-o-animation-delay\", delay + 's').css(\r\n");
      out.write("\t\t\t\t\t\t\"animation-delay\", delay + 's').addClass('animated');\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})(jQuery);\r\n");
      out.write("\r\n");
      out.write("\t/**\r\n");
      out.write("\t * Created by Kupletsky Sergey on 04.09.14.\r\n");
      out.write("\t *\r\n");
      out.write("\t * Ripple-effect animation\r\n");
      out.write("\t * Tested and working in: ?IE9+, Chrome (Mobile + Desktop), ?Safari, ?Opera, ?Firefox.\r\n");
      out.write("\t * JQuery plugin add .ink span in element with class .ripple-effect\r\n");
      out.write("\t * Animation work on CSS3 by add/remove class .animate to .ink span\r\n");
      out.write("\t */\r\n");
      out.write("\r\n");
      out.write("\t(function($) {\r\n");
      out.write("\t\t$(\".ripple-effect\").click(function(e) {\r\n");
      out.write("\t\t\tvar rippler = $(this);\r\n");
      out.write("\r\n");
      out.write("\t\t\t// create .ink element if it doesn't exist\r\n");
      out.write("\t\t\tif (rippler.find(\".ink\").length == 0) {\r\n");
      out.write("\t\t\t\trippler.append(\"<span class='ink'></span>\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar ink = rippler.find(\".ink\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t// prevent quick double clicks\r\n");
      out.write("\t\t\tink.removeClass(\"animate\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t// set .ink diametr\r\n");
      out.write("\t\t\tif (!ink.height() && !ink.width()) {\r\n");
      out.write("\t\t\t\tvar d = Math.max(rippler.outerWidth(), rippler.outerHeight());\r\n");
      out.write("\t\t\t\tink.css({\r\n");
      out.write("\t\t\t\t\theight : d,\r\n");
      out.write("\t\t\t\t\twidth : d\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t// get click coordinates\r\n");
      out.write("\t\t\tvar x = e.pageX - rippler.offset().left - ink.width() / 2;\r\n");
      out.write("\t\t\tvar y = e.pageY - rippler.offset().top - ink.height() / 2;\r\n");
      out.write("\r\n");
      out.write("\t\t\t// set .ink position and add class .animate\r\n");
      out.write("\t\t\tink.css({\r\n");
      out.write("\t\t\t\ttop : y + 'px',\r\n");
      out.write("\t\t\t\tleft : x + 'px'\r\n");
      out.write("\t\t\t}).addClass(\"animate\");\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})(jQuery);\r\n");
      out.write("\r\n");
      out.write("\tvar compare = { // Declare compare object\r\n");
      out.write("\t\tname : function(a, b) { // Add a method called name\r\n");
      out.write("\t\t\ta = a.replace(/^the /i, ''); // Remove The from start of parameter\r\n");
      out.write("\t\t\tb = b.replace(/^the /i, ''); // Remove The from start of parameter\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (a < b) { // If value a is less than value b\r\n");
      out.write("\t\t\t\treturn -1; // Return -1\r\n");
      out.write("\t\t\t} else { // Otherwise\r\n");
      out.write("\t\t\t\treturn a > b ? 1 : 0; // If a is greater than b return 1 OR\r\n");
      out.write("\t\t\t} // if they are the same return 0\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tduration : function(a, b) { // Add a method called duration\r\n");
      out.write("\t\t\ta = a.split(':'); // Split the time at the colon\r\n");
      out.write("\t\t\tb = b.split(':'); // Split the time at the colon\r\n");
      out.write("\r\n");
      out.write("\t\t\ta = Number(a[0]) * 60 + Number(a[1]); // Convert the time to seconds\r\n");
      out.write("\t\t\tb = Number(b[0]) * 60 + Number(b[1]); // Convert the time to seconds\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn a - b; // Return a minus b\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tdate : function(a, b) { // Add a method called date\r\n");
      out.write("\t\t\ta = new Date(a); // New Date object to hold the date\r\n");
      out.write("\t\t\tb = new Date(b); // New Date object to hold the date\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn a - b; // Return a minus b\r\n");
      out.write("\t\t}\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\t$('.sortable').each(function() {\r\n");
      out.write("\t\tvar $table = $(this); // This sortable table\r\n");
      out.write("\t\tvar $tbody = $table.find('tbody'); // Store table body\r\n");
      out.write("\t\tvar $controls = $table.find('th'); // Store table headers\r\n");
      out.write("\t\tvar rows = $tbody.find('tr').toArray(); // Store array containing rows\r\n");
      out.write("\r\n");
      out.write("\t\t$controls.on('click', function() { // When user clicks on a header\r\n");
      out.write("\t\t\tvar $header = $(this); // Get the header\r\n");
      out.write("\t\t\tvar order = $header.data('sort'); // Get value of data-sort attribute\r\n");
      out.write("\t\t\tvar column; // Declare variable called column\r\n");
      out.write("\r\n");
      out.write("\t\t\t// If selected item has ascending or descending class, reverse contents\r\n");
      out.write("\t\t\tif ($header.is('.ascending') || $header.is('.descending')) {\r\n");
      out.write("\t\t\t\t$header.toggleClass('ascending descending'); // Toggle to other class\r\n");
      out.write("\t\t\t\t$tbody.append(rows.reverse()); // Reverse the array\r\n");
      out.write("\t\t\t} else { // Otherwise perform a sort                            \r\n");
      out.write("\t\t\t\t$header.addClass('ascending'); // Add class to header\r\n");
      out.write("\t\t\t\t// Remove asc or desc from all other headers\r\n");
      out.write("\t\t\t\t$header.siblings().removeClass('ascending descending');\r\n");
      out.write("\t\t\t\tif (compare.hasOwnProperty(order)) { // If compare object has method\r\n");
      out.write("\t\t\t\t\tcolumn = $controls.index(this); // Search for columnâ€™s index no\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\trows.sort(function(a, b) { // Call sort() on rows array\r\n");
      out.write("\t\t\t\t\t\ta = $(a).find('td').eq(column).text(); // Get text of column in row a\r\n");
      out.write("\t\t\t\t\t\tb = $(b).find('td').eq(column).text(); // Get text of column in row b\r\n");
      out.write("\t\t\t\t\t\treturn compare[order](a, b); // Call compare method\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$tbody.append(rows);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/include/contents.jsp(25,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/include/contents.jsp(25,6) '${newlyBoard}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${newlyBoard}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/include/contents.jsp(25,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("s");
      // /WEB-INF/jsp/include/contents.jsp(25,6) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/jsp/include/contents.jsp(29,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setVar("date");
      // /WEB-INF/jsp/include/contents.jsp(29,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.regDate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/jsp/include/contents.jsp(29,8) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yy/MM/dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }
}
