/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2017-12-01 07:44:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1507863366000L));
    _jspx_dependants.put("jar:file:/C:/!SHOU/work/jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mini2-home/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/!SHOU/work/jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mini2-home/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"homeBtn\" style=\"font-size: 25px;\">\r\n");
      out.write("\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main/main.do\" style=\"color: white; text-shadow: 0 0 2px black;\">\r\n");
      out.write("\t\t<i class=\"fa fa-home fa-fw\" aria-hidden=\"true\"></i>홈으로\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-lg-6\">\r\n");
      out.write("\t    <div class=\"input-group\">\r\n");
      out.write("\t      <input type=\"text\" class=\"form-control\" id=\"target\" placeholder=\"Search for...\">\r\n");
      out.write("\t      <span class=\"input-group-btn\">\r\n");
      out.write("\t        <button id=\"search\" class=\"btn btn-default\" type=\"button\">\r\n");
      out.write("\t        <i class=\"fa fa-search fa-spin\" aria-hidden=\"true\"></i>&nbsp;검색</button>\r\n");
      out.write("\t      </span>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <!-- 검색결과 창 -->\r\n");
      out.write("\t    <div class=\"result_container\"></div>\r\n");
      out.write("\t  \r\n");
      out.write("\t  <button onclick=\"document.getElementById('serchDetail').style.display='block'\" class=\"w3-button w3-black\" style=\"float: right;\">검색옵션 설정</button>\r\n");
      out.write("\t  <div id=serchDetail class=\"w3-modal w3-animate-opacity\">\r\n");
      out.write("\t    <div class=\"w3-modal-content w3-card-4\">\r\n");
      out.write("\t      <header class=\"w3-container w3-teal\"> \r\n");
      out.write("\t        <span onclick=\"document.getElementById('serchDetail').style.display='none'\" \r\n");
      out.write("\t        class=\"w3-button w3-large w3-display-topright\">&times;</span>\r\n");
      out.write("\t        <h2>옵션을 설정해주세요</h2>\r\n");
      out.write("\t      </header>\r\n");
      out.write("\t      <div class=\"w3-container\" align=\"center\">\r\n");
      out.write("\t      \t<p>\r\n");
      out.write("\t\t        <span>\r\n");
      out.write("\t\t        \t<select id=\"option\">\r\n");
      out.write("\t\t        \t\t<option value=\"title\">제목</option>\r\n");
      out.write("\t\t        \t\t<option value=\"writer\">작성자</option>\r\n");
      out.write("\t\t        \t\t<option value=\"contents\">내용</option>\r\n");
      out.write("\t\t        \t\t<option value=\"titleContents\">제목+내용</option>\r\n");
      out.write("\t\t        \t</select>\r\n");
      out.write("\t\t        \t<select id=\"when\">\r\n");
      out.write("\t\t\t        \t<option value=\"when1\">최근 15일 동안</option>\r\n");
      out.write("\t\t\t        \t<option value=\"when2\">최근 1개월 동안</option>\r\n");
      out.write("\t\t\t        \t<option value=\"when3\">최근 3개월 동안</option>\r\n");
      out.write("\t\t\t        \t<option value=\"when4\">최근 6개월 동안</option>\r\n");
      out.write("\t\t\t        \t<option value=\"when5\">1년 이상 전 동안</option>\r\n");
      out.write("\t\t\t        \t<option value=\"when6\">2년 이상 전 동안</option>\r\n");
      out.write("\t\t        \t</select>\r\n");
      out.write("\t\t    \t</span>\r\n");
      out.write("\t    \t</p>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\tvar path = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".logout\").click(function(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: path+\"/member/logout.json\",\r\n");
      out.write("\t\t\tsuccess: function(){\r\n");
      out.write("\t\t\t\tlocation.href=path+\"/main/main.do\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t// 검색창 모션\r\n");
      out.write("\tfunction viewSerchDetail(){\r\n");
      out.write("\t\tvar $serachDetail = $(\".serach-detail\");\r\n");
      out.write("\t\tvar $serchDetailBtn = $(\".serchDetailBtn\");\r\n");
      out.write("\t\tif($serachDetail.attr(\"id\")==\"serachTypeHidden\"){\r\n");
      out.write("\t\t\t$serachDetail.attr(\"id\", \"serachTypeShow\");\r\n");
      out.write("\t\t\t$serchDetailBtn.attr(\"id\", \"serachBtnShow\");\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\t$serachDetail.attr(\"id\", \"serachTypeHidden\");\r\n");
      out.write("\t\t\t$serchDetailBtn.attr(\"id\", \"serachBtnHidden\");\t\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t$(\"#search\").click(function (e) {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: path + \"/search/search.json\",\r\n");
      out.write("\t\t\tdata: \"target=\"+$(\"#target\").val()+\"&option=\"+$(\"#option > option:selected\").val(),\r\n");
      out.write("\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t$(\".result_container > table\").html(\"\");\r\n");
      out.write("\t\t\t\tvar tableStart = \"<table class='searchList'>\";\r\n");
      out.write("\t\t\t\tvar tableEnd = \"</table>\";\r\n");
      out.write("\t\t\t\tvar tableContents = \"\";\r\n");
      out.write("\t\t\t\tif(data.length == 0){\r\n");
      out.write("\t\t\t\t\ttableContents = \"<tr><th>검색된 결과가 없습니다.</th><td>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tconsole.log($(\"#option > option:selected\").val());\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor (let ele of data) {\r\n");
      out.write("\t\t\t\t\tvar date = new Date(ele.regDate).toLocaleDateString();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\ttableContents += \r\n");
      out.write("\t\t\t\t\t\"<tr><th>글쓴이</th><td>\"+ele.writer+\r\n");
      out.write("\t\t\t\t\t\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\"<th>제목</th><a href='#'><td>\"+ele.title+\r\n");
      out.write("\t\t\t\t\t\"</td></a>\"+\r\n");
      out.write("\t\t\t\t\t\"<th>날짜</th><td>\"+date+\r\n");
      out.write("\t\t\t\t\t\"</td></tr>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\".result_container\").append(tableStart + tableContents + tableEnd);\r\n");
      out.write("\t\t\t\t$(\".result_container > table\").fadeToggle();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#target\").keyup(function (e) {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: path + \"/search/search.json\",\r\n");
      out.write("\t\t\t\tdata: \"target=\"+$(\"#target\").val()+\r\n");
      out.write("\t\t\t\t\t  \"&option=\"+$(\"#option > option:selected\").val()+\r\n");
      out.write("\t\t\t\t\t  \"&when=\"+$(\"#when > option:selected\").val(),\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\t$(\".result_container\").html(\"\");\r\n");
      out.write("\t\t\t\t\tvar tableStart = \"<table class='searchList'>\";\r\n");
      out.write("\t\t\t\t\tvar tableEnd = \"</table>\";\r\n");
      out.write("\t\t\t\t\tvar tableContents = \"\";\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(data.length == 0){\r\n");
      out.write("\t\t\t\t\t\ttableContents = \"<tr><th>검색된 결과가 없습니다.</th><td>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tfor (let ele of data) {\r\n");
      out.write("\t\t\t\t\t\tvar date = new Date(ele.regDate).toLocaleDateString();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ttableContents += \r\n");
      out.write("\t\t\t\t\t\t\"<tr onclick='#'><th>글쓴이</th><td>\"+ele.writer+\r\n");
      out.write("\t\t\t\t\t\t\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\"<th>제목</th><td>\"+ele.title+\r\n");
      out.write("\t\t\t\t\t\t\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\"<th>날짜</th><td>\"+date+\r\n");
      out.write("\t\t\t\t\t\t\"</td></tr>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\".result_container\").append(tableStart + tableContents + tableEnd);\r\n");
      out.write("\t\t\t\t\t$(\".result_container > table\").fadeToggle();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#target\").focusout(function () {\r\n");
      out.write("\t\t$(\".result_container > table\").fadeToggle();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#target\").focusin(function () {\r\n");
      out.write("\t\t$(\".result_container > table\").fadeToggle();\r\n");
      out.write("\t});\r\n");
      out.write("\tvar popOption = \"width=370, height=360, resizable=no, scrollbars=no, status=no;\"; \r\n");
      out.write("\t$(\".signUp\").click(function() {\r\n");
      out.write("\t\twindow.open(path + \"/member/main.do\",\"\", popOption);\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\tif($.cookie(\"id\")) {\r\n");
      out.write("\t\t\t\t\t\t$(\"#id\").val($.cookie(\"id\"));\r\n");
      out.write("\t\t\t\t\t\t$(\"#login_chk\").prop(\"checked\", \"true\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".btn_global\").click(function () {\r\n");
      out.write("\t\t\t\t\t\tif(!$(\"#id\").val()) {$(\"#err_empty_id\").css(\"display\", \"\"); return;}\r\n");
      out.write("\t\t\t\t\t\telse $(\"#err_empty_id\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t\t\t\tif(!$(\"#pw\").val()) {$(\"#err_empty_pw\").css(\"display\", \"\"); return;}\r\n");
      out.write("\t\t\t\t\t\telse $(\"#err_empty_pw\").css(\"display\", \"none\");\r\n");
      out.write("\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\turl: path+\"/member/login.json\",\r\n");
      out.write("\t\t\t\t\t\t\tdata: \"chk=\"+$(\"#login_chk\").prop(\"checked\")+\"&id=\"+$(\"#id\").val()+\"&pass=\"+$(\"#pw\").val(),\r\n");
      out.write("\t\t\t\t\t\t\tsuccess: function (data) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif(data) {alert(\"로그인 성공\"); location.href = path+\"/main/main.do\";}\r\n");
      out.write("\t\t\t\t\t\t\t\telse alert(\"로그인 실패\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\r\n");
          out.write("\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\t\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/jsp/include/header.jsp(58,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<div class=\"w3-card-2 w3-display-topright\" style=\"width:100px; z-index: 3000; background: green;\">\r\n");
          out.write("\t\t\t    <header class=\"w3-container w3-light-grey\">\r\n");
          out.write("\t\t\t      <h4>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h4>\r\n");
          out.write("\t\t\t    </header>\r\n");
          out.write("\t\t\t    <div class=\"w3-container\">\r\n");
          out.write("\t\t\t      <p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("\t\t\t      <hr>\r\n");
          out.write("\t\t\t      <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/images/img_avatar3.png\" class=\"w3-left w3-circle w3-margin-right\" style=\"width:60px\">\r\n");
          out.write("\t\t\t      <p style=\"font-size: xx-small;\" align=\"left\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.email1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.email2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p><br>\r\n");
          out.write("\t\t\t    </div>\r\n");
          out.write("\t\t\t    <button class=\"logout\">로그아웃</button>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<div class=\"logform\" style=\"z-index: 3000\" >\r\n");
          out.write("\t\t\t<div class=\"w3-container\">\r\n");
          out.write("\t\t\t  <button onclick=\"document.getElementById('login').style.display='block'\" class=\"w3-button w3-green w3-large\">Login</button>\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t  <div id=\"login\" class=\"w3-modal\">\r\n");
          out.write("\t\t\t    <div class=\"w3-modal-content w3-card-4 w3-animate-zoom\" style=\"max-width:600px\">\r\n");
          out.write("\t\t\t\r\n");
          out.write("\t\t\t      <div class=\"w3-center\"><br>\r\n");
          out.write("\t\t\t        <span onclick=\"document.getElementById('login').style.display='none'\" class=\"w3-button w3-xlarge w3-hover-red w3-display-topright\" title=\"Close Modal\">&times;</span>\r\n");
          out.write("\t\t\t        <img alt=\"로그인창\" style=\"width:30%\" class=\"w3-circle w3-margin-top\">\r\n");
          out.write("\t\t\t      </div>\r\n");
          out.write("\t\t\t      \r\n");
          out.write("\t\t        <div class=\"w3-section\">\r\n");
          out.write("\t\t          <label><b>아이디</b></label>\r\n");
          out.write("\t\t          <input class=\"w3-input w3-border w3-margin-bottom\" type=\"text\" id=\"id\" name=\"id\" tabindex=\"7\" accesskey=\"L\" placeholder=\"아이디를 입력하세요.\" class=\"int\" maxlength=\"41\" value=\"\">\r\n");
          out.write("\t\r\n");
          out.write("\t\t          <label><b>비밀번호</b></label>\r\n");
          out.write("\t\t          <input class=\"w3-input w3-border\" type=\"password\" id=\"pw\" name=\"pw\" tabindex=\"8\" placeholder=\"비밀번호를 입력하세요\" class=\"int\" maxlength=\"16\">\r\n");
          out.write("\t\t      \r\n");
          out.write("\t\t          <input type=\"button\" title=\"로그인\" alt=\"로그인\" tabindex=\"12\" value=\"로그인\" class=\"btn_global w3-button w3-block w3-green w3-section w3-padding\">\r\n");
          out.write("\t\t          <button class=\"signUp w3-button w3-block w3-green w3-section w3-padding\">회원가입</button>\r\n");
          out.write("\t\t          <input class=\"w3-check w3-margin-top\" type=\"checkbox\" id=\"login_chk\" name=\"nvlong\" class=\"\" tabindex=\"9\" value=\"off\">\r\n");
          out.write("\t\t\t\t  <label for=\"login_chk\" id=\"label_login_chk\" class=\"sp\">로그인 상태 유지</label>\r\n");
          out.write("\t\t\t\t  \r\n");
          out.write("\t\t        </div>\r\n");
          out.write("\t\t      \r\n");
          out.write("\t\t\r\n");
          out.write("\t\t      <div class=\"w3-container w3-border-top w3-padding-16 w3-light-grey\">\r\n");
          out.write("\t\t        <button onclick=\"document.getElementById('login').style.display='none'\" type=\"button\" class=\"w3-button w3-red\">취소</button>\r\n");
          out.write("\t\t        <span class=\"w3-right w3-padding w3-hide-small\">비밀번호를 <a href=\"#\">잃어버렸습니까?</a></span>\r\n");
          out.write("\t\t      </div>\r\n");
          out.write("\t\t      \r\n");
          out.write("\t\t    </div>\r\n");
          out.write("  \t\t</div>\r\n");
          out.write("\t</div>\r\n");
          out.write("\t<!-- 로그인폼 -->\t\t\r\n");
          out.write("</div>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
