<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

<table border="1">
	<tr>
		<td>게시판</td>
		<td>글글글글글글글글글글글글글글글글글글글글글글</td>
	</tr>
	<tr>
		<td>게시판</td>
		<td>글글글글글글글글글글글글글글글글글글글글글글글</td>
	</tr>
	<tr>
		<td>게시판</td>
		<td>글글글글글글글글글글글글글글글글글글글글글글글</td>
	</tr>
	<tr>
		<td>게시판</td>
		<td>글</td>
	</tr>
	<tr>
		<td>게시판</td>
		<td>글글글글글글글글글글글글글글글글글글글글글글글</td>
	</tr>
	<tr>
		<td>게시판</td>
		<td>글글글글글글글글글글글글글글글글글글글글글글글</td>
	</tr>
	<tr>
		<td>게시판</td>
		<td>글글글글글글글글글글글글글글글글글글글글글글글</td>
	</tr>
	<tr>
		<td>게시판</td>
		<td>글글글글글글글글글글글글글글글글글글글글글글글</td>
	</tr>
	<tr>
		<td>게시판</td>
		<td>글글글글글글글글글글글글글글글글글글글글글글글</td>
	</tr>
	<tr>
		<td>게시판</td>
		<td>글글글글글글글글글글글글글글글글글글글글글글글</td>
	</tr>
</table>